[tool.poetry]
name = "ex1"
version = "0.1.0"
description = "Matrix data analysis using numpy, pandas and matplotlib"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.1.0"
numpy = "^1.25.0"
matplotlib = "^3.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"